### ISSUE TITLE
Tmux: Page is dead

### ISSUE THREAD

**Issue by witeshadow** [danielshahaf/taskswamp#2]
Any kind of keyboard input makes tmux show "Page is dead"

It also shows 
`r/home/chris/bin/taskswamp/bin/forever:6: read-only variable: _`

under '4 tasks'

**Comment by danielshahaf** [comment]
Does this patch help?

``` diff
diff --git a/bin/forever b/bin/forever
index a2466cc..15cde02 100755
--- a/bin/forever
+++ b/bin/forever
@@ -3,4 +3,5 @@
 # This script runs a command and prompts the user.  If the user types
 # 'y' then exit.  If the user types anything else, loop.

-while clear; date; "$@" ; ! read -q _; do done
+local unused
+while clear; date; "$@" ; ! read -q unused; do done
```

**Comment by witeshadow** [comment]
That did not appear to change anything for me.

**Comment by danielshahaf** [comment]
Well, there is no other `_` variable in the codebase.  Perhaps you didn't restart the `forever` script?  Try killing the tmux session (`tmux kill-session -t task`, not just detaching it) and restarting it.

Also what is that stray leading `r` in front of your error message?

**Comment by witeshadow** [comment]
Ok, it must not have been restarted. It appears to work OK now. No idea on the 'r' but it was there.
