### ISSUE TITLE
Any chance to make this work with fish?

### ISSUE THREAD

**Issue by arooni** [danielshahaf/taskswamp#5]
love the idea... but doesn't seem to work with fish shell on os x.

**Comment by danielshahaf** [comment]
> love the idea... but doesn't seem to work with fish shell on os x.

The only shell-specific part is `bin/forever`, which is a `#!zsh`
script.  It really is a zsh script: it uses the `read -q` construct
which is not part of `sh`'s specification.  You can't run it in other
shells.

Just install zsh.  You do not need to chsh; you just need to have
a `zsh` binary in your $PATH.
